services:
  - type: web
    name: smart-farmer-procurement
    env: python
    buildCommand: pip install -r requirements.txt && python database/seed_data.py
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
